/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package managers;

import com.nitdlibrary.MainScreen;
import com.nitdlibrary.NITDLibrary;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author MAYANK
 */
public class ConfigManager extends javax.swing.JFrame {
    String mailSMTP,passwordSMTP,passwordLogin,passwordDB, welcomePicPath;
    int sem2013,year2013;
    
    
    /**
     * Creates new form ConfigManager
     */
    public ConfigManager() {
        try {
            setVisible(true);
            initComponents();
            updateFields();
        } catch (IOException ex) {
            Logger.getLogger(ConfigManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * Update the values from Config.java into the textboxes
     * @throws IOException 
     */
    private void updateFields() throws IOException
    {
         /**
         * initializing local variables
         */
         welcomePicPath=Config.welcomeScreenPicPath ;
          passwordDB=Config.dbPassword ;
         mailSMTP = Config.sessionEmail;
        passwordSMTP=Config.sessionPassword;
         year2013 =Config.year2013;
        sem2013 = Config.sem2013  ;
        passwordLogin = Config.getPassword();
        name.setText(Config.librarianName);
        email.setText(Config.librarianEmail);
        phone.setText(Config.librarianPhone);
        loginName.setText(Config.loginName);
        
        issueDuration.setValue(new Integer(Config.studentIssueDuration));
        issueLimit.setValue(new Integer(Config.issueLimitStudent));
        fineRate.setValue(new Integer(Config.ChARGEPERDAY));
        
        incrementLabel.setText("The 2013-2017 B.Tech Batch is in Semester : " + Config.sem2013 + " and Year : " + Config.year2013);
        
        emailSMTP.setText(Config.sessionEmail);
        
        driver.setText(Config.dbDriver);
        dbConnectionString.setText(Config.dbConnecionString);
        dbUserName.setText(Config.dbUserName);
        
        welcomePic.setIcon(new ImageIcon(ImageIO.read(new File(Config.welcomeScreenPicPath))));
       
    }
    /**
     * change the base statement in incrementLabel
     */
    private void updateBase()
    {
        incrementLabel.setText("The 2013-2017 B.Tech Batch is in Semester : " + sem2013 + " and Year : " + year2013);
    }
    /**
     * This Method Resized the Image
     * @param srcImg
     * @param w
     * @param h
     * @return 
     */
    private Image getScaledImage(Image srcImg, int w, int h){
    BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
    Graphics2D g2 = resizedImg.createGraphics();
    g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
    g2.drawImage(srcImg, 0, 0, w, h, null);
    g2.dispose();
    return resizedImg;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeLoginPassDialog = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        oldPass = new javax.swing.JPasswordField();
        newPass = new javax.swing.JPasswordField();
        newPassRe = new javax.swing.JPasswordField();
        changeSMTPinfo = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sessionEmailText = new javax.swing.JTextField();
        sessionPassText = new javax.swing.JPasswordField();
        emailSessionChange = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        loginName = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        issueDuration = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        issueLimit = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        fineRate = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        increaseSem = new javax.swing.JButton();
        decreaseSem = new javax.swing.JButton();
        increaseYear = new javax.swing.JButton();
        decreaseYear = new javax.swing.JButton();
        incrementLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        changeSMTP = new javax.swing.JButton();
        emailSMTP = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        driver = new javax.swing.JTextField();
        dbUserName = new javax.swing.JTextField();
        dbConnectionString = new javax.swing.JTextField();
        changeDBPassword = new javax.swing.JButton();
        createDatabase = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        welcomePic = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        changeWelcomePicButton = new javax.swing.JButton();

        changeLoginPassDialog.setMinimumSize(new java.awt.Dimension(350, 280));

        jLabel11.setText("Enter Old Password :");

        jLabel17.setText("Enter New Password :");

        jLabel19.setText("Re-Enter New Password :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Change Login Password");

        jButton2.setText("Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changeLoginPassDialogLayout = new javax.swing.GroupLayout(changeLoginPassDialog.getContentPane());
        changeLoginPassDialog.getContentPane().setLayout(changeLoginPassDialogLayout);
        changeLoginPassDialogLayout.setHorizontalGroup(
            changeLoginPassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeLoginPassDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(156, 156, 156))
            .addGroup(changeLoginPassDialogLayout.createSequentialGroup()
                .addGroup(changeLoginPassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeLoginPassDialogLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(changeLoginPassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(changeLoginPassDialogLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(newPassRe, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(changeLoginPassDialogLayout.createSequentialGroup()
                                .addGroup(changeLoginPassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel11))
                                .addGap(35, 35, 35)
                                .addGroup(changeLoginPassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(changeLoginPassDialogLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel20)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        changeLoginPassDialogLayout.setVerticalGroup(
            changeLoginPassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeLoginPassDialogLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel20)
                .addGap(33, 33, 33)
                .addGroup(changeLoginPassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(changeLoginPassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(changeLoginPassDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(newPassRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        changeSMTPinfo.setMinimumSize(new java.awt.Dimension(525, 250));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Change E-Mail Settings");

        jLabel22.setText("E-Mail ID :");

        jLabel23.setText("This E-Mail Id will be used to send Email's to students when a Book is Issued/Returned");

        jLabel24.setText("Password :");

        emailSessionChange.setText("Change");
        emailSessionChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailSessionChangeActionPerformed(evt);
            }
        });

        jLabel25.setText("* use a gmail account");

        javax.swing.GroupLayout changeSMTPinfoLayout = new javax.swing.GroupLayout(changeSMTPinfo.getContentPane());
        changeSMTPinfo.getContentPane().setLayout(changeSMTPinfoLayout);
        changeSMTPinfoLayout.setHorizontalGroup(
            changeSMTPinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeSMTPinfoLayout.createSequentialGroup()
                .addGroup(changeSMTPinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeSMTPinfoLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changeSMTPinfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23))
                    .addGroup(changeSMTPinfoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(changeSMTPinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(changeSMTPinfoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel24))
                            .addComponent(jLabel22))
                        .addGap(42, 42, 42)
                        .addGroup(changeSMTPinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailSessionChange)
                            .addGroup(changeSMTPinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sessionEmailText)
                                .addComponent(sessionPassText, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeSMTPinfoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(66, 66, 66))
        );
        changeSMTPinfoLayout.setVerticalGroup(
            changeSMTPinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeSMTPinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(changeSMTPinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(sessionEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(changeSMTPinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(sessionPassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(emailSessionChange)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Settings");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Librarian/Login Details"));

        jLabel2.setText("Name :");

        jLabel3.setText("Login Name :");

        jLabel4.setText("Password :");

        jLabel5.setText("E-Mail ID :");

        jLabel6.setText("Contact Number :");

        jButton8.setText("Change");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(name))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addGap(0, 38, Short.MAX_VALUE))
                            .addComponent(loginName))))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(loginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Issue Parameters "));

        jLabel7.setText("No of Days for which a book can be issued without fine :");

        jLabel8.setText("Maximum number of books that students can issue :");

        jLabel9.setText("Fine Rate (Rs/Day) :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fineRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(issueDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(issueLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fineRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Annual/Semester Increments"));

        jLabel10.setText("Base : ");

        increaseSem.setText("Sem ++");
        increaseSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseSemActionPerformed(evt);
            }
        });

        decreaseSem.setText("Sem --");
        decreaseSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseSemActionPerformed(evt);
            }
        });

        increaseYear.setText("Year ++");
        increaseYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseYearActionPerformed(evt);
            }
        });

        decreaseYear.setText("Year --");
        decreaseYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(incrementLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(increaseSem)
                        .addGap(18, 18, 18)
                        .addComponent(decreaseSem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(increaseYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decreaseYear)))
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(incrementLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(increaseSem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(increaseYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(decreaseSem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(decreaseYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "E-Mail/SMTP Settings"));

        jLabel12.setText("E-Mail Address :");

        changeSMTP.setText("Change");
        changeSMTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSMTPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailSMTP, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(changeSMTP)
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailSMTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(changeSMTP))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Back-End Setup "));

        jLabel13.setText("Driver :");

        jLabel14.setText("Connection String :");

        jLabel15.setText("UserName :");

        jLabel16.setText("Password :");

        changeDBPassword.setText("Change");
        changeDBPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDBPasswordActionPerformed(evt);
            }
        });

        createDatabase.setText("Create Database");
        createDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDatabaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(driver, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dbConnectionString)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeDBPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGap(30, 30, 30))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dbConnectionString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(changeDBPassword)
                    .addComponent(createDatabase))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton7.setText("Save and Close");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        welcomePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomePic.setText("LOC pic");
        welcomePic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel18.setText("Welcome Screen Pic :");

        changeWelcomePicButton.setText("Change");
        changeWelcomePicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeWelcomePicButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeWelcomePicButton)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(welcomePic, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(changeWelcomePicButton))
                .addGap(24, 24, 24)
                .addComponent(welcomePic, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
            Config.librarianName = name.getText();
            Config.librarianEmail = email.getText();
            Config.librarianPhone = phone.getText();
            Config.loginName = loginName.getText();
            
            Config.studentIssueDuration = (Integer)issueDuration.getValue();
            Config.issueLimitStudent = (Integer)issueLimit.getValue();
            Config.ChARGEPERDAY=(Integer)fineRate.getValue();
            
            
            
            Config.sessionEmail = emailSMTP.getText();
            
            Config.dbDriver = driver.getText();
            Config.dbConnecionString = dbConnectionString.getText();
            Config.dbUserName = dbUserName.getText();
            
            Config.welcomeScreenPicPath = welcomePicPath;
            Config.dbPassword = passwordDB;
            Config.sessionEmail = mailSMTP;
            Config.sessionPassword = passwordSMTP;
            Config.setPassword(passwordLogin);
            
            /**
             * refactoring database
             */
           try {
            Connection library = NITDLibrary.createConnection();
            Statement query = library.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = query.executeQuery("select * from student" );
            int year,sem;
               System.out.println(Config.year2013 - year2013);
            while(rs.next())
            {
               
                year = rs.getInt("Year") - Config.year2013 + year2013;
                sem = rs.getInt("Semester") - Config.sem2013 + sem2013;
                rs.updateInt("Year",year);
                rs.updateInt("Semester",sem);
                rs.updateRow();
            }
            
               System.out.println("SETTINGS : year and sem updated in database");
        } catch (SQLException ex) {
            Logger.getLogger(ConfigManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ConfigManager.class.getName()).log(Level.SEVERE, null, ex);
        }
           Config.year2013 = year2013;
            Config.sem2013 = sem2013;
            serializeConfig();
           // dispose();
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(oldPass.getText().compareTo(Config.getPassword())==0)
        {
            if(newPass.getText().compareTo(newPassRe.getText())==0)
            {
                passwordLogin = newPass.getText();
            changeLoginPassDialog.setVisible(false);
            }else
                com.nitdlibrary.Error.errorDialog("Passwords Do Not Match");
        }
        else
            com.nitdlibrary.Error.errorDialog("Incorrect Old Password");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void emailSessionChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailSessionChangeActionPerformed
        Config.sessionEmail = sessionEmailText.getText();
        Config.sessionPassword = sessionPassText.getText();
        changeSMTPinfo.setVisible(false);
    }//GEN-LAST:event_emailSessionChangeActionPerformed

    private void increaseSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseSemActionPerformed
        sem2013++;
        updateBase();
        
    }//GEN-LAST:event_increaseSemActionPerformed

    private void decreaseSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseSemActionPerformed
        sem2013--;
        updateBase();
    }//GEN-LAST:event_decreaseSemActionPerformed

    private void increaseYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseYearActionPerformed
        year2013++;
        updateBase();
    }//GEN-LAST:event_increaseYearActionPerformed

    private void decreaseYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseYearActionPerformed
        year2013--;
        updateBase();
    }//GEN-LAST:event_decreaseYearActionPerformed

    private void changeSMTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSMTPActionPerformed
        changeSMTPinfo.setVisible(true);
    }//GEN-LAST:event_changeSMTPActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        changeLoginPassDialog.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void changeDBPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDBPasswordActionPerformed
        passwordDB = JOptionPane.showInputDialog(null,"Enter Database Password","Change Password",JOptionPane.OK_OPTION);
    }//GEN-LAST:event_changeDBPasswordActionPerformed

    private void changeWelcomePicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeWelcomePicButtonActionPerformed
        JFileChooser welcomeChooser = new JFileChooser();
        int returnVal = welcomeChooser.showDialog(this, "choose");
        welcomeChooser.setFileFilter(Config.filter);
        
        if(returnVal == JFileChooser.APPROVE_OPTION);
        {
            File f = welcomeChooser.getSelectedFile();
            try {
                Image pic = ImageIO.read(f);
                Image resizedPic = getScaledImage(pic, 204,256);
                welcomePic.setIcon(new ImageIcon(resizedPic));
            } catch (IOException ex) {
                Logger.getLogger(ConfigManager.class.getName()).log(Level.SEVERE, null, ex);
            }
            welcomePicPath = f.getAbsolutePath();
            
        }
    }//GEN-LAST:event_changeWelcomePicButtonActionPerformed

    private void createDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDatabaseActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/",Config.dbUserName,Config.dbPassword);
            Statement query = con.createStatement();
           String databaseQuery = "create database if not exists library";
           String databaseQuery1 = "use library";
            String booksQuery = "CREATE TABLE IF NOT EXISTS `library`.`books` (\n" +
"  `acc_no` INT(11) NOT NULL,\n" +
"  `title` VARCHAR(45) NOT NULL,\n" +
"  `author2` VARCHAR(45) NULL DEFAULT 'N/A',\n" +
"  `author` VARCHAR(20) NULL DEFAULT NULL,\n" +
"  `author3` VARCHAR(45) NULL DEFAULT 'N/A',\n" +
"  `classno` VARCHAR(10) NULL DEFAULT 'N/A',\n" +
"  `subject` VARCHAR(50) NULL DEFAULT NULL,\n" +
"  `subject_code` VARCHAR(10) NULL DEFAULT 'N/A',\n" +
"  `pagination` INT(11) NULL DEFAULT NULL,\n" +
"  `ISBN` VARCHAR(45) NULL DEFAULT NULL,\n" +
"  `acc_date` DATE NULL DEFAULT NULL,\n" +
"  `history` VARCHAR(500) NULL DEFAULT 'N/A' COMMENT 'stores code as comma separated array. retrieve using regular expressions.',\n" +
"  `publisher` VARCHAR(45) NULL DEFAULT 'N/A',\n" +
"  `price` FLOAT NULL DEFAULT NULL,\n" +
"  `edition` VARCHAR(10) NULL DEFAULT NULL,\n" +
"  `year` YEAR NULL DEFAULT NULL,\n" +
"  `location` VARCHAR(45) NULL DEFAULT NULL,\n" +
"  `status` INT(11) NULL DEFAULT NULL,\n" +
"  `status_tag` INT(11) NULL DEFAULT NULL,\n" +
"  PRIMARY KEY (`acc_no`))\n" +
"ENGINE = InnoDB\n" +
"DEFAULT CHARACTER SET = utf8";
            String studentQuery = "CREATE TABLE IF NOT EXISTS `library`.`student` (\n" +
"  `roll_no` INT(11) NOT NULL,\n" +
"  `First Name` VARCHAR(45) NOT NULL,\n" +
"  `Middle Name` VARCHAR(45) NULL DEFAULT NULL,\n" +
"  `Last Name` VARCHAR(45) NULL DEFAULT NULL,\n" +
"  `Fathers Name` VARCHAR(45) NULL DEFAULT NULL,\n" +
"  `books issued` VARCHAR(500) NULL DEFAULT ',',\n" +
"  `current_issued_no` INT(11) NULL DEFAULT '0',\n" +
"  `Gender` VARCHAR(6) NULL DEFAULT NULL,\n" +
"  `Date Of Birth` DATE NULL DEFAULT NULL,\n" +
"  `Category` VARCHAR(6) NULL DEFAULT NULL,\n" +
"  `Primary Address` VARCHAR(400) NULL DEFAULT NULL,\n" +
"  `Mailing Address` VARCHAR(400) NULL DEFAULT NULL,\n" +
"  `Contact Number` VARCHAR(11) NULL DEFAULT NULL,\n" +
"  `E-Mail` VARCHAR(45) NULL DEFAULT NULL,\n" +
"  `Programme` VARCHAR(10) NULL DEFAULT NULL,\n" +
"  `Branch` VARCHAR(10) NULL DEFAULT NULL,\n" +
"  `Year` INT(11) NULL DEFAULT NULL,\n" +
"  `Semester` INT(11) NULL DEFAULT NULL,\n" +
"  `Card Numbers` VARCHAR(20) NULL DEFAULT NULL,\n" +
"  `Cards Issued` INT(11) NULL DEFAULT NULL,\n" +
"  `pic_path` VARCHAR(150) NULL DEFAULT NULL,\n" +
"  PRIMARY KEY (`roll_no`))\n" +
"ENGINE = InnoDB\n" +
"DEFAULT CHARACTER SET = utf8";
            String issueQuery = "CREATE TABLE IF NOT EXISTS `library`.`issue` (\n" +
"  `issue_id` INT(11) NOT NULL AUTO_INCREMENT,\n" +
"  `acc_no` INT(11) NOT NULL,\n" +
"  `issuer_id` INT(11) NOT NULL,\n" +
"  `issue_date` DATE NOT NULL,\n" +
"  `return_date` DATE NULL DEFAULT NULL,\n" +
"  `due_date` DATE NULL DEFAULT NULL,\n" +
"  PRIMARY KEY (`issue_id`))\n" +
"ENGINE = InnoDB\n" +
"AUTO_INCREMENT = 12\n" +
"DEFAULT CHARACTER SET = utf8";
            String subjectQuery = "CREATE TABLE IF NOT EXISTS `library`.`subjects` (\n" +
"  `subject_id` INT(11) NOT NULL AUTO_INCREMENT,\n" +
"  `subject_code` VARCHAR(10) NOT NULL,\n" +
"  `subject_name` VARCHAR(45) NULL DEFAULT NULL,\n" +
"  `subject_class_no` VARCHAR(45) NULL DEFAULT NULL,\n" +
"  PRIMARY KEY (`subject_id`),\n" +
"  UNIQUE INDEX `subject_code` (`subject_code` ASC),\n" +
"  UNIQUE INDEX `subject_class_no` (`subject_class_no` ASC),\n" +
"  UNIQUE INDEX `subject_class_no_2` (`subject_class_no` ASC))\n" +
"ENGINE = InnoDB\n" +
"AUTO_INCREMENT = 6\n" +
"DEFAULT CHARACTER SET = utf8";
            query.executeUpdate(databaseQuery);
            query.execute(databaseQuery1);
            query.executeUpdate(booksQuery);
            query.executeUpdate(studentQuery);
            query.executeUpdate(issueQuery);
            query.executeUpdate(subjectQuery);
            JOptionPane.showMessageDialog(null,"Database and Tables successfully created ");
        } catch (SQLException ex) {
            com.nitdlibrary.Error.errorDialog(ex.getMessage());
            Logger.getLogger(ConfigManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ConfigManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createDatabaseActionPerformed

    public void serializeConfig() 
    {
        try {
            Config configurations = new Config();
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(ConfigManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(ConfigManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeDBPassword;
    private javax.swing.JDialog changeLoginPassDialog;
    private javax.swing.JButton changeSMTP;
    private javax.swing.JDialog changeSMTPinfo;
    private javax.swing.JButton changeWelcomePicButton;
    private javax.swing.JButton createDatabase;
    private javax.swing.JTextField dbConnectionString;
    private javax.swing.JTextField dbUserName;
    private javax.swing.JButton decreaseSem;
    private javax.swing.JButton decreaseYear;
    private javax.swing.JTextField driver;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailSMTP;
    private javax.swing.JButton emailSessionChange;
    private javax.swing.JSpinner fineRate;
    private javax.swing.JButton increaseSem;
    private javax.swing.JButton increaseYear;
    private javax.swing.JLabel incrementLabel;
    private javax.swing.JSpinner issueDuration;
    private javax.swing.JSpinner issueLimit;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField loginName;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField newPassRe;
    private javax.swing.JPasswordField oldPass;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField sessionEmailText;
    private javax.swing.JPasswordField sessionPassText;
    private javax.swing.JLabel welcomePic;
    // End of variables declaration//GEN-END:variables
}
