/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package managers;
import com.nitdlibrary.NITDLibrary;
import com.nitdlibrary.ReportGenerator;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import org.joda.time.LocalDate;
/**
 *
 * @author MAYANK
 */
public class Register extends javax.swing.JFrame {
    ResultSet registerResultSet = null;
    Connection library;
    LocalDate today = new LocalDate(new java.util.Date());
    LocalDate currentDate;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        currentDate = today;
        
    try {
        library = NITDLibrary.createConnection();
    } catch (Exception ex) {
        Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
    }
    /**
     * Load Data
     */    
    try {
            loadTableData();
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    /**
     * Set Enter Action
     */
      addKeyListener(new KeyListener() {

            @Override
            public void keyTyped(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode()==KeyEvent.VK_ENTER)
                {
                    System.out.println("Focussed on : " + getFocusOwner().toString());
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * This method obtains resultset and populates table
     */
    private void loadTableData() throws SQLException
    {
        PreparedStatement overDueQuery = library.prepareStatement("select issue.issue_id,books.title,student.`First Name`,student.`Last Name`,student.`roll_no`,student.Programme,student.Branch,student.Year,books.acc_no,books.author,issue.due_date,issue.return_date from books,student,issue where issue.issue_date= ? and books.acc_no = issue.acc_no and student.roll_no = issue.issuer_id order by issue.issue_id");
        overDueQuery.setString(1,currentDate.toString("yyyy-MM-dd"));
        registerResultSet=overDueQuery.executeQuery(); 
        registerPage.setModel(DbUtils.resultSetToTableModel(registerResultSet));
        date.setText("DATE : " + currentDate.toString("MMM d,yyyy"));
        Integer[] fields = new Integer[2];
        fields[0]=10;
        fields[1]=11;
        registerResultSet.beforeFirst();
        registerPage.setModel(managers.Config.changeResultSetDateFormat(registerResultSet, registerPage.getModel(), fields));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        registerPage = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        navPrev = new javax.swing.JButton();
        navNext = new javax.swing.JButton();
        navGoto = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        print = new javax.swing.JButton();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        registerPage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        registerPage.setEditingColumn(0);
        registerPage.setRowSelectionAllowed(true);
        registerPage.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        registerPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerPageMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(registerPage);

        jToolBar1.setRollover(true);

        navPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/navigation_previous.png"))); // NOI18N
        navPrev.setFocusable(false);
        navPrev.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navPrev.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        navPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navPrevActionPerformed(evt);
            }
        });
        jToolBar1.add(navPrev);

        navNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/navigation_next.png"))); // NOI18N
        navNext.setFocusable(false);
        navNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        navNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navNextActionPerformed(evt);
            }
        });
        jToolBar1.add(navNext);

        navGoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/navigation_goto.png"))); // NOI18N
        navGoto.setFocusable(false);
        navGoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        navGoto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        navGoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navGotoActionPerformed(evt);
            }
        });
        jToolBar1.add(navGoto);
        jToolBar1.add(dateChooser);

        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        print.setFocusable(false);
        print.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        print.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jToolBar1.add(print);

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setText("Date :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(581, 581, 581))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navPrevActionPerformed
        currentDate=currentDate.minusDays(1);
        try {
            loadTableData();
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_navPrevActionPerformed

    private void navNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navNextActionPerformed
        currentDate = currentDate.plusDays(1);
        try {
            loadTableData();
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_navNextActionPerformed

    private void navGotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navGotoActionPerformed
        currentDate = new LocalDate(dateChooser.getDate());
        try {
            loadTableData();
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_navGotoActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        Component printComponent = this;
        PrintUtilities.printComponent(registerPage);
    }//GEN-LAST:event_printActionPerformed

    private void registerPageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerPageMousePressed
        if(evt.getClickCount()==2)
        {
            new ReportGenerator((int)registerPage.getValueAt(registerPage.getSelectedRow(),0)).setVisible(true);
        }
    }//GEN-LAST:event_registerPageMousePressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        System.out.println(getFocusOwner().toString());
        System.out.println("chala");
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton navGoto;
    private javax.swing.JButton navNext;
    private javax.swing.JButton navPrev;
    private javax.swing.JButton print;
    private javax.swing.JTable registerPage;
    // End of variables declaration//GEN-END:variables
}
